spring:
  profiles:
    active: local
  application:
    name: user-crud
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#  liquibase:
#    change-log: db/changelog/liquibase-changeLog.xml
##    Liquibase turn on or off
#    enabled: false
#    driver-class-name: org.postgresql.Driver